import { JSX } from "react";
import {
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiReact,
  SiRedux,
  SiNodedotjs,
  SiNestjs,
  SiPython,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiDocker,
  SiJest,
  SiCypress,
  SiSlack,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGraphql,
  SiTailwindcss,
  SiSass,
  SiBootstrap,
  SiFigma,
  SiLinux,
  SiMacos,
  SiTrello,
  SiJira,
  SiOpenai,
  SiPrisma,
  SiFastify,
  SiTypeorm,
  SiRedis,
  SiPostman,
} from "react-icons/si";
import {
  FaTools,
  FaServer,
  FaDatabase,
  FaProjectDiagram,
  FaCode,
  FaCogs,
  FaRobot,
  FaLink,
  FaBug,
  FaFolderOpen,
} from "react-icons/fa";

export const skillIcons: Record<string, JSX.Element> = {
  JavaScript: <SiJavascript />,
  TypeScript: <SiTypescript />,
  HTML: <SiHtml5 />,
  CSS: <SiCss3 />,
  Python: <SiPython />,
  "React.js": <SiReact />,
  Redux: <SiRedux />,
  "RTK Query": <SiRedux />,
  "React Query": <SiReact />,
  "Nest.js": <SiNestjs />,
  "Node.js": <SiNodedotjs />,
  PostgreSQL: <SiPostgresql />,
  MongoDB: <SiMongodb />,
  MySQL: <SiMysql />,
  Docker: <SiDocker />,
  Jest: <SiJest />,
  Cypress: <SiCypress />,
  Slack: <SiSlack />,
  Git: <SiGit />,
  GitHub: <SiGithub />,
  GitLab: <SiGitlab />,
  GraphQL: <SiGraphql />,
  Tailwind: <SiTailwindcss />,
  SASS: <SiSass />,
  Bootstrap: <SiBootstrap />,
  Figma: <SiFigma />,
  Linux: <SiLinux />,
  MacOS: <SiMacos />,
  Trello: <SiTrello />,
  Jira: <SiJira />,
  "OpenAI Whisper": <SiOpenai />,
  Prisma: <SiPrisma />,
  Fastify: <SiFastify />,
  TypeORM: <SiTypeorm />,
  Redis: <SiRedis />,
  Postman: <SiPostman />,
  "Shadcn/ui": <SiTailwindcss />,
  "RESTful APIs": <FaLink />,
  "Google Chat": <SiSlack />,
  Java: <FaCode />,
  SQL: <FaDatabase />,
  "Express.js": <FaServer />,
  Mongoose: <FaDatabase />,
  K6: <FaBug />,
  Lighthouse: <FaBug />,
};

export const categoryIcons: Record<string, JSX.Element> = {
  "Programming Languages": <FaCode />,
  Frontend: <FaFolderOpen />,
  Backend: <FaServer />,
  AI: <FaRobot />,
  API: <FaLink />,
  "Version Control": <FaCogs />,
  Database: <FaDatabase />,
  Tools: <FaTools />,
  OS: <FaCogs />,
  Testing: <FaBug />,
  PM: <FaProjectDiagram />,
};
